version: '3'
services:
  tutor_tupy:
    build: .

    container_name: tutor_tupy

    command: python3 bottle_server.py -O

    #entrypoint: /bin/sh
    #stdin_open: true
    #tty: true

    volumes:
      - ../../uerjInterpreter/tupy:/opt/app/tupy

    ports:
      - "8003:8003"

    working_dir: /opt/app

    logging:
      driver: journald
